### PR TITLE
removed service definition class parameters

### PR DESCRIPTION
**Pull request by sjopet**

### CODE REVIEW

**Comment by nacmartin** [comment]
Thanks. I have added added a406a031310cf60ff45c5ade013c9cbdee1af49e so it works as well in new environments. I have checked in sf3.1 and 4, and I think it should work in sf2.8 as well (the last available version I had in git of an example with Liform was in 3.1).

**Comment by sjopet** [comment]
That should work fine for 2.8 I think, I'll check later today

**Comment by sjopet** [comment]
Added a pr to fix the liform reference in the compiler pass @nacmartin could you bump the version after merging?

**Comment by nacmartin** [comment]
Sure, thanks! I will try it briefly just to be sure and release a new version with this. Tagging this version will also help as I am working in the choice fields expanded/multiple, that is being a pain and will introduce a (small) compatibility break.

**Pull request merged**
