### PR TITLE
fixed liform service reference in compiler pass

### PR DESCRIPTION
**Pull request by sjopet**

### CODE REVIEW

**Comment by sjopet** [comment]
WIP: found a weird issue with the TransformerCompilerPass i need to fix first.

**Comment by nacmartin** [comment]
Ok, fine 👍

**Comment by sjopet** [comment]
Fixed the issue with TransformerCompilerPass not registering more then 1 tag per transformer. I would like to add some tests for this but don't have the time right now.

**Comment by nacmartin** [comment]
Thanks! Indeed it is quite annoying to test these parts.

**Comment by nacmartin** [comment]
Included in v0.11.1 🎉

**Pull request merged**
